// 
// Decompiled by Procyon v0.5.36
// 

package DrawUtil;

import java.awt.GraphicsEnvironment;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Graphics;
import java.awt.Component;
import javax.swing.JFrame;
import java.util.ArrayList;
import java.awt.Color;

public class MoColors
{
    public static Color maroon;
    public static Color darkRed;
    public static Color fireBrick;
    public static Color red;
    public static Color salmon;
    public static Color tomato;
    public static Color coral;
    public static Color orangeRed;
    public static Color deepPink;
    public static Color hotPink;
    public static Color crimson;
    public static Color IndianRed;
    public static Color lightCoral;
    public static Color mistyRose;
    public static Color darkSalmon;
    public static Color lightSalmon;
    public static Color paleVioletRed;
    public static Color pink;
    public static Color lightPink;
    public static Color chocolate;
    public static Color sandyBrown;
    public static Color darkOrange;
    public static Color orange;
    public static Color brown;
    public static Color rosyBrown;
    public static Color sienna;
    public static Color saddleBrown;
    public static Color peachpuff;
    public static Color peru;
    public static Color bisque;
    public static Color burlywood;
    public static Color tan;
    public static Color blanchedAlmond;
    public static Color moccasin;
    public static Color wheat;
    public static Color darkGoldenrod;
    public static Color goldenrod;
    public static Color gold;
    public static Color olive;
    public static Color yellow;
    public static Color cornsilk;
    public static Color khaki;
    public static Color lemonChiffon;
    public static Color paleGoldenrod;
    public static Color darkKhaki;
    public static Color beige;
    public static Color lightGoldenrodYellow;
    public static Color lightYellow;
    public static Color yellowGreen;
    public static Color greenYellow;
    public static Color chartreuse;
    public static Color green;
    public static Color lime;
    public static Color limeGreen;
    public static Color springGreen;
    public static Color oliveDrab;
    public static Color darkOliveGreen;
    public static Color darkSeaGreen;
    public static Color darkGreen;
    public static Color forestGreen;
    public static Color lightGreen;
    public static Color paleGreen;
    public static Color seaGreen;
    public static Color mediumSeaGreen;
    public static Color mediumAquamarine;
    public static Color turquoise;
    public static Color lightSeaGreen;
    public static Color darkCyan;
    public static Color aqua;
    public static Color darkTurquoise;
    public static Color deepSkyBlue;
    public static Color dodgerBlue;
    public static Color royalBlue;
    public static Color navy;
    public static Color darkBlue;
    public static Color mediumBlue;
    public static Color blue;
    public static Color aquamarine;
    public static Color darkSlateGray;
    public static Color paleTurqouise;
    public static Color lightCyan;
    public static Color cadetBlue;
    public static Color powderBlue;
    public static Color lightBlue;
    public static Color skyBlue;
    public static Color lightSkyBlue;
    public static Color steelBlue;
    public static Color lightSteelBlue;
    public static Color cornflowerBlue;
    public static Color lavender;
    public static Color midnightBlue;
    public static Color slateBlue;
    public static Color darkSlateBlue;
    public static Color mediumSlateBlue;
    public static Color blueViolet;
    public static Color darkOrchid;
    public static Color darkViolet;
    public static Color purple;
    public static Color darkMagenta;
    public static Color magenta;
    public static Color mediumVioletRed;
    public static Color mediumPurple;
    public static Color indigo;
    public static Color mediumOrchid;
    public static Color plum;
    public static Color violet;
    public static Color thistle;
    public static Color orchid;
    public static Color snow;
    public static Color seaShell;
    public static Color linen;
    public static Color antiqueWhite;
    public static Color navajoWhite;
    public static Color papayaWhip;
    public static Color oldlace;
    public static Color floralWhite;
    public static Color ivory;
    public static Color honeydew;
    public static Color mintCream;
    public static Color azure;
    public static Color aliceBlue;
    public static Color slateGray;
    public static Color lightSlateGray;
    public static Color ghostWhite;
    public static Color lavenderBlush;
    public static Color black;
    public static Color dimgray;
    public static Color gray;
    public static Color darkGray;
    public static Color silver;
    public static Color lightGray;
    public static Color gainsboro;
    public static Color whiteSmoke;
    public static Color white;
    public static ArrayList<Color> redColors;
    public static ArrayList<Color> orangeColors;
    public static ArrayList<Color> yellowColors;
    public static ArrayList<Color> greenColors;
    public static ArrayList<Color> blueColors;
    public static ArrayList<Color> purpleColors;
    public static ArrayList<Color> whiteColors;
    public static ArrayList<String> redNames;
    public static ArrayList<String> orangeNames;
    public static ArrayList<String> yellowNames;
    public static ArrayList<String> greenNames;
    public static ArrayList<String> blueNames;
    public static ArrayList<String> purpleNames;
    public static ArrayList<String> whiteNames;
    public static ArrayList<ArrayList<Color>> allColors;
    public static ArrayList<ArrayList<String>> allNames;
    
    static {
        MoColors.maroon = Color.decode("#800000");
        MoColors.darkRed = Color.decode("#8B0000");
        MoColors.fireBrick = Color.decode("#B22222");
        MoColors.red = Color.decode("#FF0000");
        MoColors.salmon = Color.decode("#FA8072");
        MoColors.tomato = Color.decode("#FF6347");
        MoColors.coral = Color.decode("#FF7F50");
        MoColors.orangeRed = Color.decode("#FF4500");
        MoColors.deepPink = Color.decode("#FF1493");
        MoColors.hotPink = Color.decode("#FF69B4");
        MoColors.crimson = Color.decode("#DC143C");
        MoColors.IndianRed = Color.decode("#CD5C5C");
        MoColors.lightCoral = Color.decode("#F08080");
        MoColors.mistyRose = Color.decode("#FFE4E1");
        MoColors.darkSalmon = Color.decode("#E9967A");
        MoColors.lightSalmon = Color.decode("#FFA07A");
        MoColors.paleVioletRed = Color.decode("#DB7093");
        MoColors.pink = Color.decode("#FFC0CB");
        MoColors.lightPink = Color.decode("#FFB6C1");
        MoColors.chocolate = Color.decode("#D2691E");
        MoColors.sandyBrown = Color.decode("#F4A460");
        MoColors.darkOrange = Color.decode("#FF8C00");
        MoColors.orange = Color.decode("#FFA500");
        MoColors.brown = Color.decode("#A52A2A");
        MoColors.rosyBrown = Color.decode("#BC8F8F");
        MoColors.sienna = Color.decode("#A0522D");
        MoColors.saddleBrown = Color.decode("#8B4513");
        MoColors.peachpuff = Color.decode("#FFDAB9");
        MoColors.peru = Color.decode("#CD853F");
        MoColors.bisque = Color.decode("#FFE4C4");
        MoColors.burlywood = Color.decode("#DEB887");
        MoColors.tan = Color.decode("#D2B48C");
        MoColors.blanchedAlmond = Color.decode("#FAEBD7");
        MoColors.moccasin = Color.decode("#FFE4B5");
        MoColors.wheat = Color.decode("#F5DEB3");
        MoColors.darkGoldenrod = Color.decode("#B8860B");
        MoColors.goldenrod = Color.decode("#DAA520");
        MoColors.gold = Color.decode("#FFD700");
        MoColors.olive = Color.decode("#808000");
        MoColors.yellow = Color.decode("#FFFF00");
        MoColors.cornsilk = Color.decode("#FFF8DC");
        MoColors.khaki = Color.decode("#F0E68C");
        MoColors.lemonChiffon = Color.decode("#FFFACD");
        MoColors.paleGoldenrod = Color.decode("#EEE8AA");
        MoColors.darkKhaki = Color.decode("#BDB76B");
        MoColors.beige = Color.decode("#F5F5DC");
        MoColors.lightGoldenrodYellow = Color.decode("#FAFAD2");
        MoColors.lightYellow = Color.decode("#FFFFE0");
        MoColors.yellowGreen = Color.decode("#9ACD32");
        MoColors.greenYellow = Color.decode("#ADFF2F");
        MoColors.chartreuse = Color.decode("#7FFF00");
        MoColors.green = Color.decode("#008000");
        MoColors.lime = Color.decode("#00FF00");
        MoColors.limeGreen = Color.decode("#32CD32");
        MoColors.springGreen = Color.decode("#00FF7F");
        MoColors.oliveDrab = Color.decode("#6B8E23");
        MoColors.darkOliveGreen = Color.decode("#556B2F");
        MoColors.darkSeaGreen = Color.decode("#8FBC8F");
        MoColors.darkGreen = Color.decode("#006400");
        MoColors.forestGreen = Color.decode("#228B22");
        MoColors.lightGreen = Color.decode("#90EE90");
        MoColors.paleGreen = Color.decode("#98FB98");
        MoColors.seaGreen = Color.decode("#2E8B57");
        MoColors.mediumSeaGreen = Color.decode("#3CB371");
        MoColors.mediumAquamarine = Color.decode("#66CDAA");
        MoColors.turquoise = Color.decode("#40E0D0");
        MoColors.lightSeaGreen = Color.decode("#20B2AA");
        MoColors.darkCyan = Color.decode("#008B8B");
        MoColors.aqua = Color.decode("#00FFFF");
        MoColors.darkTurquoise = Color.decode("#00CED1");
        MoColors.deepSkyBlue = Color.decode("#00BFFF");
        MoColors.dodgerBlue = Color.decode("#1E90FF");
        MoColors.royalBlue = Color.decode("#4169E1");
        MoColors.navy = Color.decode("#000080");
        MoColors.darkBlue = Color.decode("#00008B");
        MoColors.mediumBlue = Color.decode("#0000CD");
        MoColors.blue = Color.decode("#0000FF");
        MoColors.aquamarine = Color.decode("#7FFFD4");
        MoColors.darkSlateGray = Color.decode("#2F4F4F");
        MoColors.paleTurqouise = Color.decode("#AFEEEE");
        MoColors.lightCyan = Color.decode("#E0FFFF");
        MoColors.cadetBlue = Color.decode("#5F9EA0");
        MoColors.powderBlue = Color.decode("#B0E0E6");
        MoColors.lightBlue = Color.decode("#ADD8E6");
        MoColors.skyBlue = Color.decode("#87CEEB");
        MoColors.lightSkyBlue = Color.decode("#87CEFA");
        MoColors.steelBlue = Color.decode("#4682B4");
        MoColors.lightSteelBlue = Color.decode("#B0C4DE");
        MoColors.cornflowerBlue = Color.decode("#6495ED");
        MoColors.lavender = Color.decode("#E6E6FA");
        MoColors.midnightBlue = Color.decode("#191970");
        MoColors.slateBlue = Color.decode("#6A5ACD");
        MoColors.darkSlateBlue = Color.decode("#483D8B");
        MoColors.mediumSlateBlue = Color.decode("#7B68EE");
        MoColors.blueViolet = Color.decode("#8A2BE2");
        MoColors.darkOrchid = Color.decode("#9932CC");
        MoColors.darkViolet = Color.decode("#9400D3");
        MoColors.purple = Color.decode("#800080");
        MoColors.darkMagenta = Color.decode("#8B008B");
        MoColors.magenta = Color.decode("#FF00FF");
        MoColors.mediumVioletRed = Color.decode("#C71585");
        MoColors.mediumPurple = Color.decode("#9370DB");
        MoColors.indigo = Color.decode("#4B0082");
        MoColors.mediumOrchid = Color.decode("#BA55D3");
        MoColors.plum = Color.decode("#DDA0DD");
        MoColors.violet = Color.decode("#EE82EE");
        MoColors.thistle = Color.decode("#D8BFD8");
        MoColors.orchid = Color.decode("#DA70D6");
        MoColors.snow = Color.decode("#FFFAFA");
        MoColors.seaShell = Color.decode("#FFF5EE");
        MoColors.linen = Color.decode("#FAF0E6");
        MoColors.antiqueWhite = Color.decode("#FAEBD7");
        MoColors.navajoWhite = Color.decode("#FFDEAD");
        MoColors.papayaWhip = Color.decode("#FFEFD5");
        MoColors.oldlace = Color.decode("#FDF5E6");
        MoColors.floralWhite = Color.decode("#FFFAF0");
        MoColors.ivory = Color.decode("#FFFFF0");
        MoColors.honeydew = Color.decode("#F0FFF0");
        MoColors.mintCream = Color.decode("#F5FFFA");
        MoColors.azure = Color.decode("#F0FFFF");
        MoColors.aliceBlue = Color.decode("#F0F8FF");
        MoColors.slateGray = Color.decode("#708090");
        MoColors.lightSlateGray = Color.decode("#778899");
        MoColors.ghostWhite = Color.decode("#F8F8FF");
        MoColors.lavenderBlush = Color.decode("#E6E6FA");
        MoColors.black = Color.decode("#000000");
        MoColors.dimgray = Color.decode("#696969");
        MoColors.gray = Color.decode("#808080");
        MoColors.darkGray = Color.decode("#A9A9A9");
        MoColors.silver = Color.decode("#C0C0C0");
        MoColors.lightGray = Color.decode("#D3D3D3");
        MoColors.gainsboro = Color.decode("#DCDCDC");
        MoColors.whiteSmoke = Color.decode("#F5F5F5");
        MoColors.white = Color.decode("#FFFFFF");
        MoColors.redColors = new ArrayList<Color>();
        MoColors.orangeColors = new ArrayList<Color>();
        MoColors.yellowColors = new ArrayList<Color>();
        MoColors.greenColors = new ArrayList<Color>();
        MoColors.blueColors = new ArrayList<Color>();
        MoColors.purpleColors = new ArrayList<Color>();
        MoColors.whiteColors = new ArrayList<Color>();
        MoColors.redNames = new ArrayList<String>();
        MoColors.orangeNames = new ArrayList<String>();
        MoColors.yellowNames = new ArrayList<String>();
        MoColors.greenNames = new ArrayList<String>();
        MoColors.blueNames = new ArrayList<String>();
        MoColors.purpleNames = new ArrayList<String>();
        MoColors.whiteNames = new ArrayList<String>();
        MoColors.allColors = new ArrayList<ArrayList<Color>>();
        MoColors.allNames = new ArrayList<ArrayList<String>>();
        
        MoColors.redColors.add(MoColors.maroon);
        MoColors.redColors.add(MoColors.darkRed);
        MoColors.redColors.add(MoColors.fireBrick);
        MoColors.redColors.add(MoColors.red);
        MoColors.redColors.add(MoColors.salmon);
        MoColors.redColors.add(MoColors.tomato);
        MoColors.redColors.add(MoColors.coral);
        MoColors.redColors.add(MoColors.orangeRed);
        MoColors.redColors.add(MoColors.deepPink);
        MoColors.redColors.add(MoColors.hotPink);
        MoColors.redColors.add(MoColors.mediumVioletRed);
        MoColors.redColors.add(MoColors.crimson);
        MoColors.redColors.add(MoColors.IndianRed);
        MoColors.redColors.add(MoColors.lightCoral);
        MoColors.redColors.add(MoColors.mistyRose);
        MoColors.redColors.add(MoColors.darkSalmon);
        MoColors.redColors.add(MoColors.lightSalmon);
        MoColors.redColors.add(MoColors.paleVioletRed);
        MoColors.redColors.add(MoColors.pink);
        MoColors.redColors.add(MoColors.lightPink);
        MoColors.redNames.add("maroon");
        MoColors.redNames.add("darkRed");
        MoColors.redNames.add("fireBrick");
        MoColors.redNames.add("red");
        MoColors.redNames.add("salmon");
        MoColors.redNames.add("tomato");
        MoColors.redNames.add("coral");
        MoColors.redNames.add("orangeRed");
        MoColors.redNames.add("deepPink");
        MoColors.redNames.add("hotPink");
        MoColors.redNames.add("mediumVioletRed");
        MoColors.redNames.add("crimson");
        MoColors.redNames.add("IndianRed");
        MoColors.redNames.add("lightCoral");
        MoColors.redNames.add("mistyRose");
        MoColors.redNames.add("darkSalmon");
        MoColors.redNames.add("lightSalmon");
        MoColors.redNames.add("paleVioletRed");
        MoColors.redNames.add("pink");
        MoColors.redNames.add("lightPink");
        MoColors.orangeColors.add(MoColors.orangeRed);
        MoColors.orangeColors.add(MoColors.chocolate);
        MoColors.orangeColors.add(MoColors.sandyBrown);
        MoColors.orangeColors.add(MoColors.darkOrange);
        MoColors.orangeColors.add(MoColors.orange);
        MoColors.orangeColors.add(MoColors.brown);
        MoColors.orangeColors.add(MoColors.rosyBrown);
        MoColors.orangeColors.add(MoColors.sienna);
        MoColors.orangeColors.add(MoColors.saddleBrown);
        MoColors.orangeColors.add(MoColors.peachpuff);
        MoColors.orangeColors.add(MoColors.peru);
        MoColors.orangeColors.add(MoColors.bisque);
        MoColors.orangeColors.add(MoColors.burlywood);
        MoColors.orangeColors.add(MoColors.tan);
        MoColors.orangeColors.add(MoColors.blanchedAlmond);
        MoColors.orangeColors.add(MoColors.moccasin);
        MoColors.orangeColors.add(MoColors.wheat);
        MoColors.orangeNames.add("orangeRed");
        MoColors.orangeNames.add("chocolate");
        MoColors.orangeNames.add("sandyBrown");
        MoColors.orangeNames.add("darkOrange");
        MoColors.orangeNames.add("orange");
        MoColors.orangeNames.add("brown");
        MoColors.orangeNames.add("rosyBrown");
        MoColors.orangeNames.add("sienna");
        MoColors.orangeNames.add("saddleBrown");
        MoColors.orangeNames.add("peachpuff");
        MoColors.orangeNames.add("peru");
        MoColors.orangeNames.add("bisque");
        MoColors.orangeNames.add("burlywood");
        MoColors.orangeNames.add("tan");
        MoColors.orangeNames.add("blanchedAlmond");
        MoColors.orangeNames.add("moccasin");
        MoColors.orangeNames.add("wheat");
        MoColors.yellowColors.add(MoColors.darkGoldenrod);
        MoColors.yellowColors.add(MoColors.goldenrod);
        MoColors.yellowColors.add(MoColors.gold);
        MoColors.yellowColors.add(MoColors.olive);
        MoColors.yellowColors.add(MoColors.yellow);
        MoColors.yellowColors.add(MoColors.yellowGreen);
        MoColors.yellowColors.add(MoColors.cornsilk);
        MoColors.yellowColors.add(MoColors.khaki);
        MoColors.yellowColors.add(MoColors.lemonChiffon);
        MoColors.yellowColors.add(MoColors.paleGoldenrod);
        MoColors.yellowColors.add(MoColors.darkKhaki);
        MoColors.yellowColors.add(MoColors.beige);
        MoColors.yellowColors.add(MoColors.lightGoldenrodYellow);
        MoColors.yellowColors.add(MoColors.lightYellow);
        MoColors.yellowNames.add("darkGoldenrod");
        MoColors.yellowNames.add("goldenrod");
        MoColors.yellowNames.add("gold");
        MoColors.yellowNames.add("olive");
        MoColors.yellowNames.add("yellow");
        MoColors.yellowNames.add("yellowGreen");
        MoColors.yellowNames.add("cornsilk");
        MoColors.yellowNames.add("khaki");
        MoColors.yellowNames.add("lemonChiffon");
        MoColors.yellowNames.add("paleGoldenrod");
        MoColors.yellowNames.add("darkKhaki");
        MoColors.yellowNames.add("beige");
        MoColors.yellowNames.add("lightGoldenrodYellow");
        MoColors.yellowNames.add("lightYellow");
        MoColors.greenColors.add(MoColors.yellowGreen);
        MoColors.greenColors.add(MoColors.greenYellow);
        MoColors.greenColors.add(MoColors.chartreuse);
        MoColors.greenColors.add(MoColors.green);
        MoColors.greenColors.add(MoColors.lime);
        MoColors.greenColors.add(MoColors.limeGreen);
        MoColors.greenColors.add(MoColors.springGreen);
        MoColors.greenColors.add(MoColors.oliveDrab);
        MoColors.greenColors.add(MoColors.darkOliveGreen);
        MoColors.greenColors.add(MoColors.darkSeaGreen);
        MoColors.greenColors.add(MoColors.darkGreen);
        MoColors.greenColors.add(MoColors.forestGreen);
        MoColors.greenColors.add(MoColors.lightGreen);
        MoColors.greenColors.add(MoColors.paleGreen);
        MoColors.greenColors.add(MoColors.seaGreen);
        MoColors.greenColors.add(MoColors.mediumSeaGreen);
        MoColors.greenColors.add(MoColors.mediumAquamarine);
        MoColors.greenNames.add("yellowGreen");
        MoColors.greenNames.add("greenYellow");
        MoColors.greenNames.add("chartreuse");
        MoColors.greenNames.add("green");
        MoColors.greenNames.add("lime");
        MoColors.greenNames.add("limeGreen");
        MoColors.greenNames.add("springGreen");
        MoColors.greenNames.add("oliveDrab");
        MoColors.greenNames.add("darkOliveGreen");
        MoColors.greenNames.add("darkSeaGreen");
        MoColors.greenNames.add("darkGreen");
        MoColors.greenNames.add("forestGreen");
        MoColors.greenNames.add("lightGreen");
        MoColors.greenNames.add("paleGreen");
        MoColors.greenNames.add("seaGreen");
        MoColors.greenNames.add("mediumSeaGreen");
        MoColors.greenNames.add("mediumAquamarine");
        MoColors.blueColors.add(MoColors.turquoise);
        MoColors.blueColors.add(MoColors.lightSeaGreen);
        MoColors.blueColors.add(MoColors.darkCyan);
        MoColors.blueColors.add(MoColors.aqua);
        MoColors.blueColors.add(MoColors.darkTurquoise);
        MoColors.blueColors.add(MoColors.deepSkyBlue);
        MoColors.blueColors.add(MoColors.dodgerBlue);
        MoColors.blueColors.add(MoColors.royalBlue);
        MoColors.blueColors.add(MoColors.navy);
        MoColors.blueColors.add(MoColors.darkBlue);
        MoColors.blueColors.add(MoColors.mediumBlue);
        MoColors.blueColors.add(MoColors.blue);
        MoColors.blueColors.add(MoColors.aquamarine);
        MoColors.blueColors.add(MoColors.darkSlateGray);
        MoColors.blueColors.add(MoColors.paleTurqouise);
        MoColors.blueColors.add(MoColors.lightCyan);
        MoColors.blueColors.add(MoColors.cadetBlue);
        MoColors.blueColors.add(MoColors.powderBlue);
        MoColors.blueColors.add(MoColors.lightBlue);
        MoColors.blueColors.add(MoColors.skyBlue);
        MoColors.blueColors.add(MoColors.lightSkyBlue);
        MoColors.blueColors.add(MoColors.steelBlue);
        MoColors.blueColors.add(MoColors.lightSteelBlue);
        MoColors.blueColors.add(MoColors.cornflowerBlue);
        MoColors.blueColors.add(MoColors.lavender);
        MoColors.blueColors.add(MoColors.midnightBlue);
        MoColors.blueColors.add(MoColors.slateBlue);
        MoColors.blueColors.add(MoColors.darkSlateBlue);
        MoColors.blueColors.add(MoColors.mediumSlateBlue);
        MoColors.blueNames.add("turquoise");
        MoColors.blueNames.add("lightSeaGreen");
        MoColors.blueNames.add("darkCyan");
        MoColors.blueNames.add("aqua");
        MoColors.blueNames.add("darkTurquoise");
        MoColors.blueNames.add("deepSkyBlue");
        MoColors.blueNames.add("dodgerBlue");
        MoColors.blueNames.add("royalBlue");
        MoColors.blueNames.add("navy");
        MoColors.blueNames.add("darkBlue");
        MoColors.blueNames.add("mediumBlue");
        MoColors.blueNames.add("blue");
        MoColors.blueNames.add("aquamarine");
        MoColors.blueNames.add("darkSlateGray");
        MoColors.blueNames.add("paleTurqouise");
        MoColors.blueNames.add("lightCyan");
        MoColors.blueNames.add("cadetBlue");
        MoColors.blueNames.add("powderBlue");
        MoColors.blueNames.add("lightBlue");
        MoColors.blueNames.add("skyBlue");
        MoColors.blueNames.add("lightSkyBlue");
        MoColors.blueNames.add("steelBlue");
        MoColors.blueNames.add("lightSteelBlue");
        MoColors.blueNames.add("cornflowerBlue");
        MoColors.blueNames.add("lavender");
        MoColors.blueNames.add("midnightBlue");
        MoColors.blueNames.add("slateBlue");
        MoColors.blueNames.add("darkSlateBlue");
        MoColors.blueNames.add("mediumSlateBlue");
        MoColors.purpleColors.add(MoColors.blueViolet);
        MoColors.purpleColors.add(MoColors.darkOrchid);
        MoColors.purpleColors.add(MoColors.darkViolet);
        MoColors.purpleColors.add(MoColors.purple);
        MoColors.purpleColors.add(MoColors.darkMagenta);
        MoColors.purpleColors.add(MoColors.magenta);
        MoColors.purpleColors.add(MoColors.mediumVioletRed);
        MoColors.purpleColors.add(MoColors.mediumPurple);
        MoColors.purpleColors.add(MoColors.indigo);
        MoColors.purpleColors.add(MoColors.mediumOrchid);
        MoColors.purpleColors.add(MoColors.plum);
        MoColors.purpleColors.add(MoColors.violet);
        MoColors.purpleColors.add(MoColors.thistle);
        MoColors.purpleColors.add(MoColors.orchid);
        MoColors.purpleNames.add("blueViolet");
        MoColors.purpleNames.add("darkOrchid");
        MoColors.purpleNames.add("darkViolet");
        MoColors.purpleNames.add("purple");
        MoColors.purpleNames.add("darkMagenta");
        MoColors.purpleNames.add("magenta");
        MoColors.purpleNames.add("mediumVioletRed");
        MoColors.purpleNames.add("mediumPurple");
        MoColors.purpleNames.add("indigo");
        MoColors.purpleNames.add("mediumOrchid");
        MoColors.purpleNames.add("plum");
        MoColors.purpleNames.add("violet");
        MoColors.purpleNames.add("thistle");
        MoColors.purpleNames.add("orchid");
        MoColors.whiteColors.add(MoColors.snow);
        MoColors.whiteColors.add(MoColors.seaShell);
        MoColors.whiteColors.add(MoColors.linen);
        MoColors.whiteColors.add(MoColors.antiqueWhite);
        MoColors.whiteColors.add(MoColors.navajoWhite);
        MoColors.whiteColors.add(MoColors.papayaWhip);
        MoColors.whiteColors.add(MoColors.oldlace);
        MoColors.whiteColors.add(MoColors.floralWhite);
        MoColors.whiteColors.add(MoColors.ivory);
        MoColors.whiteColors.add(MoColors.honeydew);
        MoColors.whiteColors.add(MoColors.mintCream);
        MoColors.whiteColors.add(MoColors.azure);
        MoColors.whiteColors.add(MoColors.aliceBlue);
        MoColors.whiteColors.add(MoColors.slateGray);
        MoColors.whiteColors.add(MoColors.lightSlateGray);
        MoColors.whiteColors.add(MoColors.ghostWhite);
        MoColors.whiteColors.add(MoColors.lavenderBlush);
        MoColors.whiteColors.add(MoColors.black);
        MoColors.whiteColors.add(MoColors.dimgray);
        MoColors.whiteColors.add(MoColors.gray);
        MoColors.whiteColors.add(MoColors.darkGray);
        MoColors.whiteColors.add(MoColors.silver);
        MoColors.whiteColors.add(MoColors.lightGray);
        MoColors.whiteColors.add(MoColors.gainsboro);
        MoColors.whiteColors.add(MoColors.white);
        MoColors.whiteNames.add("snow");
        MoColors.whiteNames.add("seaShell");
        MoColors.whiteNames.add("linen");
        MoColors.whiteNames.add("antiqueWhite");
        MoColors.whiteNames.add("navajoWhite");
        MoColors.whiteNames.add("papayaWhip");
        MoColors.whiteNames.add("oldlace");
        MoColors.whiteNames.add("floralWhite");
        MoColors.whiteNames.add("ivory");
        MoColors.whiteNames.add("honeydew");
        MoColors.whiteNames.add("mintCream");
        MoColors.whiteNames.add("azure");
        MoColors.whiteNames.add("aliceBlue");
        MoColors.whiteNames.add("slateGray");
        MoColors.whiteNames.add("lightSlateGray");
        MoColors.whiteNames.add("ghostWhite");
        MoColors.whiteNames.add("lavenderBlush");
        MoColors.whiteNames.add("black");
        MoColors.whiteNames.add("dimgray");
        MoColors.whiteNames.add("gray");
        MoColors.whiteNames.add("darkGray");
        MoColors.whiteNames.add("silver");
        MoColors.whiteNames.add("lightGray");
        MoColors.whiteNames.add("gainsboro");
        MoColors.whiteNames.add("white");
        MoColors.allColors.add(MoColors.redColors);
        MoColors.allColors.add(MoColors.orangeColors);
        MoColors.allColors.add(MoColors.yellowColors);
        MoColors.allColors.add(MoColors.greenColors);
        MoColors.allColors.add(MoColors.blueColors);
        MoColors.allColors.add(MoColors.purpleColors);
        MoColors.allColors.add(MoColors.whiteColors);
        MoColors.allNames.add(MoColors.redNames);
        MoColors.allNames.add(MoColors.orangeNames);
        MoColors.allNames.add(MoColors.yellowNames);
        MoColors.allNames.add(MoColors.greenNames);
        MoColors.allNames.add(MoColors.blueNames);
        MoColors.allNames.add(MoColors.purpleNames);
        MoColors.allNames.add(MoColors.whiteNames);
    }
    
    public static void main(final String[] args) {
        final JFrame f = new JFrame();
        f.setTitle("Drawing Graphics in a Frame by Adding a Component");
        f.setBounds(80, 30, 1640, 960);
        f.add(new MyComponent());
        f.setVisible(true);
        f.setDefaultCloseOperation(3);
       
    }
    
    static class MyComponent extends Component
    {
        @Override
        public void paint(final Graphics g) {
            final Graphics2D g2d = (Graphics2D)g;
            final int width = 65;
            final int height = 18;
            final int spacing = 12;
            final ArrayList<RectanglePlus> coloredRectangles = new ArrayList<RectanglePlus>();
            final Font fntSmall = new Font("Arial", 0, 10);
            for (int i = 0; i < MoColors.allColors.size(); ++i) {
                for (int j = 0; j < MoColors.allColors.get(i).size(); ++j) {
                    final Color currentColor = MoColors.allColors.get(i).get(j);
                    final Color opposite = new Color((currentColor.getRed() + 128) % 256, (currentColor.getGreen() + 128) % 256, (currentColor.getBlue() + 128) % 256);
                    if (i != MoColors.allColors.size() - 1) {
                        coloredRectangles.add(new RectanglePlus(10 + i * (width + spacing), 30 + j * (height + spacing), width, height, currentColor, currentColor, false, RectanglePlus.gradientFormat.horizontal, currentColor, fntSmall, opposite, MoColors.allNames.get(i).get(j)));
                    }
                    else {
                        coloredRectangles.add(new RectanglePlus(10 + i * (width + spacing), 30 + j * (height + spacing), width, height, currentColor, currentColor, true, RectanglePlus.gradientFormat.horizontal, MoColors.dimgray, fntSmall, Color.black, MoColors.allNames.get(i).get(j)));
                    }
                }
            }
            for (int i = 0; i < coloredRectangles.size(); ++i) {
                coloredRectangles.get(i).draw(g2d);
            }
            final String[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
            final int spacing2 = 5;
            final int modVal = 760;
            g.setColor(Color.black);
            for (int k = 0; k < fonts.length; ++k) {
                g.setFont(new Font(fonts[k], 0, 12));
                final int yVal = 30 + k * (spacing2 + g.getFont().getSize());
                g.drawString(fonts[k], 80 + MoColors.allColors.size() * (width + spacing2) + 150 * (yVal / modVal), 30 + yVal % modVal);
            }
        }
    }
}
